# Generated by Django 5.2.4 on 2025-07-20 13:51

import django.db.models.deletion
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultypartimage',
            name='image',
            field=models.ImageField(upload_to=website.models.faulty_part_image_upload_path),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(upload_to=website.models.vehicle_image_upload_path),
        ),
        migrations.AlterField(
            model_name='wheelimage',
            name='image',
            field=models.ImageField(upload_to=website.models.wheel_image_upload_path),
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=website.models.vehicle_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='website.vehicle')),
            ],
        ),
    ]
