# Generated by Django 5.2.4 on 2025-07-20 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_faultypartimage_image_alter_vehicleimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='user',
        ),
    ]
